steps:
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'auth'
    args:
      [
        'build',
        '-t',
        'australia-southeast1-docker.pkg.dev/$PROJECT_ID/gnomad/gnomad-blog:$SHORT_SHA',
        '-f',
        'blog.dockerfile',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'auth'
    args:
      [
        'build',
        '-t',
        'australia-southeast1-docker.pkg.dev/$PROJECT_ID/gnomad/gnomad-blog-auth:$SHORT_SHA',
        '-f',
        'auth.dockerfile',
        '.',
      ]
images:
  - 'australia-southeast1-docker.pkg.dev/$PROJECT_ID/gnomad/gnomad-blog:$SHORT_SHA'
  - 'australia-southeast1-docker.pkg.dev/$PROJECT_ID/gnomad/gnomad-blog-auth:$SHORT_SHA'
