name: Update site
on:
  push:
    branches:
      - main
      - dev
    paths-ignore:
      - 'auth/**'

jobs:
  update-site:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'main' && 'production' || 'development' }}
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18.20.3

      - name: Get yarn cache
        id: yarn-cache
        run: |
          echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - name: Use yarn cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            yarn-

      - name: Install dependencies
        run: yarn install --frozen-lockfile --non-interactive --no-progress

      - name: Build site
        env:
          GA_TRACKING_ID: ${{ secrets.GA_TRACKING_ID }}
          BLOG_URL: ${{ vars.BLOG_URL }}
        run: |
          PATH_PREFIX="/news" yarn run build

      - name: gcloud auth
        uses: google-github-actions/auth@v2
        with:
          # Format for this secret is: projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider
          workload_identity_provider: '${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: '${{ secrets.GCS_SA_EMAIL }}'

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        
      - name: Deploy site
        uses: google-github-actions/upload-cloud-storage@v2
        with:
          path: 'public'
          destination: '${{ secrets.GCS_BUCKET }}/main'
          parent: false
          process_gcloudignore: false
          headers: |-
            cache-control: 'private, max-age=0, no-transform'
